{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"Timed out retrying after 4000ms: expected '[ <div>, 1 more... ]' to contain 'Receita invÃ¡lida!'","children":[{"name":"CT066 - Validar cadastrar nova Receita com campo valor zerado","uid":"62c2a78286676394","parentUid":"46092d106ea74b637589f09e85fab80a","status":"failed","time":{"start":1693239331170,"stop":1693239338816,"duration":7646},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"46092d106ea74b637589f09e85fab80a"},{"name":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > \n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"CT068 - Validar Cadastrar despesa com valor negativo","uid":"35851244f13a23a2","parentUid":"f97a16eb95ad012d1feaff687be66d9d","status":"failed","time":{"start":1693239338905,"stop":1693239342972,"duration":4067},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":5,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"f97a16eb95ad012d1feaff687be66d9d"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}